PROJECT_DONE = 1
PROJECT_IN_PROCESS = 2
PROJECT_FROZEN = 3

PROJECT_STATUSES = (
    (PROJECT_DONE, 'DONE'),
    (PROJECT_IN_PROCESS, 'IN_PROCESS'),
    (PROJECT_FROZEN, 'FROZEN')
)


PROJECT_DEVELOPMENT = 1
PROJECT_OPTIMIZATION = 2

PROJECT_TYPES = (
    (PROJECT_DEVELOPMENT, 'DEVELOPMENT'),
    (PROJECT_OPTIMIZATION, 'OPTIMIZATION')
)

